### ISSUE TITLE
width and height must be > 0 in dialogfragment

### ISSUE THREAD

**Issue by persiansushiant** [Manabu-GT/EtsyBlur#11]
hi thanks for your great library i just want to use dialogfragment i use it in an activity with
 BlurDialogFragment fragment = BlurDialogFragment.newInstance();
        fragment.show(getSupportFragmentManager(), "dialog");
and i get
java.lang.IllegalArgumentException: width and height must be > 0

**Comment by Manabu-GT** [comment]
Thanks for reporting the issue.

Did you experience the issue in version 0.1.2? or 0.1.1?
If so, what android os version are you using?

**Comment by persiansushiant** [comment]
0.1.1 api 18

On Tue, Aug 25, 2015 at 9:19 PM, Manabu Shimobe <notifications@github.com>
wrote:

> Thanks for reporting the issue.
>
> Did you experience the issue in version 0.1.2? or 0.1.1?
> If so, what android os version are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Manabu-GT/EtsyBlur/issues/11#issuecomment-134667922>.
>



-- 
Kamran Hatami
MBA Student at AmirKabir University
Mobile&Website Developer
www.kamranhatami.i <http://www.kamranhatami.mihanblog.com>r

**Comment by Manabu-GT** [comment]
I merged the fix in v0.1.2 to solve this issue. Can you try v0.1.2 and see if it works?

**Comment by persiansushiant** [comment]
for sure here is 1 AM ill inform you tomorrow thanks for support

On Tue, Aug 25, 2015 at 10:24 PM, Manabu Shimobe <notifications@github.com>
wrote:

> I merged the fix in v0.1.2 to solve this issue. Can you try v0.1.2 and see
> if it works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Manabu-GT/EtsyBlur/issues/11#issuecomment-134685132>.
>



-- 
Kamran Hatami
MBA Student at AmirKabir University
Mobile&Website Developer
www.kamranhatami.i <http://www.kamranhatami.mihanblog.com>r

**Comment by persiansushiant** [comment]
still have problem

On Wed, Aug 26, 2015 at 1:03 AM, Kamran Hatami <hatami.kamran@gmail.com>
wrote:

> for sure here is 1 AM ill inform you tomorrow thanks for support
>
> On Tue, Aug 25, 2015 at 10:24 PM, Manabu Shimobe <notifications@github.com
> > wrote:
>
>> I merged the fix in v0.1.2 to solve this issue. Can you try v0.1.2 and
>> see if it works?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Manabu-GT/EtsyBlur/issues/11#issuecomment-134685132>.
>>
>
>
>
> --
> Kamran Hatami
> MBA Student at AmirKabir University
> Mobile&Website Developer
> www.kamranhatami.i <http://www.kamranhatami.mihanblog.com>r
>



-- 
Kamran Hatami
MBA Student at AmirKabir University
Mobile&Website Developer
www.kamranhatami.i <http://www.kamranhatami.mihanblog.com>r

**Comment by Manabu-GT** [comment]
Hmm, Thanks. I will take a look. 
If you can share the code so that I can easily repo, that would be great.
